// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fdd111111ddf......
......fbdd1111dddf......
......fcdbfddfbdbf......
.......fbcf11fcbfff.....
.......ffb1111bcfbcf....
........fcdb1bdfbbbf....
.......ffffffffffcf.....
.....fcb1bcfffff........
.....f1b1b1ffff.........
......ffbff.............
........................
........................
........................
........................
........................
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . c c c c . . . 
. . . . . . . c c d d d d c . . 
. . . . . c c c c c c d d c . . 
. . . c c c 4 4 4 4 d c c c c c 
. . c 4 4 1 4 4 4 4 4 1 c c 4 f 
. c 4 4 4 4 1 4 4 4 4 d 1 f 4 f 
f 4 4 4 4 4 1 4 4 4 4 4 1 f 4 f 
f 4 4 f 4 4 1 4 c f 4 4 1 4 4 f 
f 4 4 4 4 4 1 c 4 f 4 4 1 f f f 
. f 4 4 4 4 1 4 4 f 4 4 d f . . 
. . f 4 4 1 4 c c 4 4 d f . . . 
. . . f d 4 4 4 4 4 4 c f . . . 
. . . . f f 4 4 4 4 c d b c . . 
. . . . . . f f f f d d d c . . 
. . . . . . . . . . c c c . . . 
`;
            case "image3":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fdd111111ddf......
......fbdd1111dddf......
......fcdbfddfbdbf......
.......fbcf11fcbfff.....
.......ffb1111bcfbcf....
........fcdb1bdfbbbf....
.......ffffffffffcf.....
.....fcb1bcfffff........
.....f1b1b1ffff.........
......ffbff.............
........................
........................
........................
........................
........................
`;
            case "image4":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . c c c c . . . 
. . . . . . . c c d d d d c . . 
. . . . . c c c c c c d d c . . 
. . . c c c 4 4 4 4 d c c c c c 
. . c 4 4 1 4 4 4 4 4 1 c c 4 f 
. c 4 4 4 4 1 4 4 4 4 d 1 f 4 f 
f 4 4 4 4 4 1 4 4 4 4 4 1 f 4 f 
f 4 4 f 4 4 1 4 c f 4 4 1 4 4 f 
f 4 4 4 4 4 1 c 4 f 4 4 1 f f f 
. f 4 4 4 4 1 4 4 f 4 4 d f . . 
. . f 4 4 1 4 c c 4 4 d f . . . 
. . . f d 4 4 4 4 4 4 c f . . . 
. . . . f f 4 4 4 4 c d b c . . 
. . . . . . f f f f d d d c . . 
. . . . . . . . . . c c c . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
